<?php

/*
 * infrawrench/sdk v1.20.0 | MIT | Copyright (c) 2026 Infrawrench LLC
 * https://github.com/Infrawrench/Infrawrench
 *
 * Generated from the Infrawrench API OpenAPI 3.1 spec (API version 1.20.0).
 *
 * DO NOT EDIT. Regenerate with:
 *   pnpm --filter @infrawrench/web generate:sdk
 *
 * Internal routes are absent by construction: the generator consumes the same
 * published spec that /openapi.json serves, which drops every operation
 * marked x-internal.
 */

declare(strict_types=1);

namespace Infrawrench\Sdk\Api;

use Infrawrench\Sdk\Internal\ApiNamespace;
use Infrawrench\Sdk\Internal\Coerce;
use Infrawrench\Sdk\Internal\RequestSpec;
use Infrawrench\Sdk\Internal\Transport;
use Infrawrench\Sdk\Model\IacImportPlanRequest;
use Infrawrench\Sdk\Model\IacImportPlanResponse;
use Infrawrench\Sdk\Model\IacReconciliationResponse;
use Infrawrench\Sdk\Model\IacResourceStatusResponse;
use Infrawrench\Sdk\RequestOptions;

/** `$client->iac` */
final class IacNamespace extends ApiNamespace
{
    /** `$client->iac->states` */
    public readonly IacStatesNamespace $states;

    public function __construct(Transport $transport)
    {
        parent::__construct($transport);
        $this->states = new IacStatesNamespace($this->transport);
    }

    /**
     * Generate Terraform import blocks for unmanaged resources
     *
     * Terraform 1.5+ `import` blocks plus the matching resource stanzas, generated by the same
     * plugin export mappers and HCL serializer that back "Export to Terraform…". Resources no
     * plugin can express are returned in `unsupported` with a reason, never dropped.
     *
     * POST /api/org/{orgId}/iac/import-plan
     *
     * Raises on 400: Bad request
     *
     * Raises on 404: Not found
     *
     * @param string|null $orgId Organization id. Defaults to the `orgId` the client was constructed with.
     * @throws \Infrawrench\Sdk\ApiException on any non-2xx response.
     * @throws \Infrawrench\Sdk\MissingParameterException if a path parameter has no value.
     */
    public function importPlan(?string $orgId = null, ?IacImportPlanRequest $body = null, ?RequestOptions $options = null): IacImportPlanResponse
    {
        $data = $this->transport->request(
            new RequestSpec(
                method: 'POST',
                path: '/api/org/{orgId}/iac/import-plan',
                pathParams: ['orgId' => $orgId],
                body: $body?->toArray(),
                hasBody: $body !== null,
            ),
            $options,
        );

        return IacImportPlanResponse::fromArray(Coerce::toArray($data));
    }

    /**
     * Classify inventory against a state document
     *
     * Every synced resource classified as managed, drifted or unmanaged against one uploaded
     * state, plus state entries with no inventory match. Unmanaged resources carry the ownership
     * and first-seen join that answers "who made this by hand, and when".
     *
     * GET /api/org/{orgId}/iac/reconciliation
     *
     * Raises on 400: Bad request
     *
     * Raises on 404: Not found
     *
     * @param string|null $orgId Organization id. Defaults to the `orgId` the client was constructed with.
     * @throws \Infrawrench\Sdk\ApiException on any non-2xx response.
     * @throws \Infrawrench\Sdk\MissingParameterException if a path parameter has no value.
     */
    public function reconciliation(string $stateId, ?string $orgId = null, ?RequestOptions $options = null): IacReconciliationResponse
    {
        $data = $this->transport->request(
            new RequestSpec(
                method: 'GET',
                path: '/api/org/{orgId}/iac/reconciliation',
                pathParams: ['orgId' => $orgId],
                query: ['stateId' => $stateId],
            ),
            $options,
        );

        return IacReconciliationResponse::fromArray(Coerce::toArray($data));
    }

    /**
     * IaC status for one resource
     *
     * The managed/unmanaged badge for a resource detail page, computed against the newest state
     * document. `status` is null when the organization has uploaded none — absence of a state is
     * not evidence of ClickOps. A query parameter rather than a path segment because composite
     * resource ids contain slashes.
     *
     * GET /api/org/{orgId}/iac/resource
     *
     * Raises on 400: Bad request
     *
     * @param string|null $orgId Organization id. Defaults to the `orgId` the client was constructed with.
     * @throws \Infrawrench\Sdk\ApiException on any non-2xx response.
     * @throws \Infrawrench\Sdk\MissingParameterException if a path parameter has no value.
     */
    public function resource(string $resourceId, ?string $orgId = null, ?RequestOptions $options = null): IacResourceStatusResponse
    {
        $data = $this->transport->request(
            new RequestSpec(
                method: 'GET',
                path: '/api/org/{orgId}/iac/resource',
                pathParams: ['orgId' => $orgId],
                query: ['resourceId' => $resourceId],
            ),
            $options,
        );

        return IacResourceStatusResponse::fromArray(Coerce::toArray($data));
    }
}
